---

#getting the current hostname
- name: checking if the hostname is already setted
  shell: hostname | grep "{{ application_type }}-{{ application_name }}" | wc -l
  register: current_hostname

#generating a random hostname
- name: generating hostname
  shell: echo "{{ application_type }}-{{ application_name }}-$(openssl rand -hex 4)"
  register: hostname_generated
  when: (current_hostname.stdout == "0")

#setting the hostname generated
- name: setting hostname
  hostname:
    name: "{{ hostname_generated.stdout }}"
  when: (current_hostname.stdout == "0")

#adding it to the hosts file
- name: add to hosts
  lineinfile: >
    dest=/etc/hosts
    regexp='^127\.0\.0\.1'
    line='127.0.0.1 localhost {{ hostname_generated.stdout }}'
    state=present
  when: (current_hostname.stdout == "0")